### ISSUE TITLE
Keymagic refuses to add km2 file

### ISSUE THREAD

**Issue by mQn9x9ne** [thantthet/keymagic#36]
Hi

I downloaded and installed Keymagic 1.5.1 on Microsoft Windows 10 Home Edition (64-bit, US English). The default keyboard is US English. The installation was successful.

Next, I downloaded a file called Tzerng_Koang.km2

However I was unable to add it to Keymagic. The error message was it already existed.

What I did next was to delete all the km2 files in the Keymagic's layout folder and tried to add Tzerng_Koang.km2. Again the same error message appeared.

How do I solve the above issue?

**Comment by thantthet** [comment]
Hello,

I just tried adding the keyboard you mentioned to keymagic 1.5.1 and I can add just fine. There could be something wrong with your system but not related to keymagic. You can try to choose different installation path when you install keymagic. If the problem persists, you can try new keymagic preview version from here: http://keymagic.net/downloads/

Hope this help!

Please do not open new issue since this doesn't look like keymagic bug.

Thanks!
