### ISSUE TITLE
KeyMagic-v2.0Pre-4 Window 10 64bit (Run at startup -> soulation)

### ISSUE THREAD

**Issue by SnowFallGameStudio** [thantthet/keymagic#54]
1.KeyMagic.exe -> Right Click -> Run as administrator -> Options -> Run at startup 
(auto <on> but u can need safe try is <off> and <on> two time check)

2.Restart the pc and desktop screen a few second late is KeyMagic application auto run is work)

**Comment by thantthet** [comment]
please reopen if this issue still exists in the latest version.

**Comment by khunteebwar** [comment]
Dear @SnowFallGameStudio , I think, I also encounter this issue as well but your method doesn't fix it on my PC. I manually have to add its shortcut to the startup for it. 

For both version 1.0.0.6 and 1.0.0.7,
The Keymagic doesn't start automatically though its "Run at Startup" is checked. In Windows Startup Setting, it is "turn on" as shown in the attached screenshot.
--------------------
For version, 1.0.0.6,
The pre-added keyboard layouts are missing after reboot. So that I manually have to download and add the keyboards.
For version, 10.0.7
Sometimes, I encountered that the Keymagic hotkeys stopped and cannot be opened ( to add/remove the keyboard layouts ). In such time, it can be opened by "Run as Administrator" but cannot switch keyboards. Removing, Re-installing it or restarting the PC doesn't fix either.  :(


![Keymagic_startup](https://user-images.githubusercontent.com/46150592/66455518-0f569200-ea91-11e9-8c3e-6ab0a66fcaa1.JPG)

**Comment by SnowFallGameStudio** [comment]
1. Keymagic doesn't start automatically, not sure you pc is over pre-loading i think , but u can try is 
![Screen Shoot 01](https://user-images.githubusercontent.com/4278893/66478673-ea7a1300-eac0-11e9-969b-6edc4ebc4418.png) , you pc is so many "High impact" and one more Reason is Windows 10 so many background run "Skype, OneDrive , Cortana, etc . . . .." 
2. pre-added keyboard layouts are missing (2.0.0.6) , i am not idea.
3. hotkeys stopped -> https://github.com/thantthet/keymagic/issues/67, Fixed later i think
4. you pc hardward information need, Cpu and ram , HDD or SDD, and windows 10 boot time, "Ctrl + Alt + Delete"  => Task Manager => Startup [Menu]=>Last Bios Time 3.3 Seconds [my pc] ,
![Screen Shoot 02](https://user-images.githubusercontent.com/4278893/66479672-fa92f200-eac2-11e9-92c0-c600828ff2cc.png)

Choice , another software
1. https://keyman.com/burmese/ , Keyman( Myanmar3 (SIL) Keyboard) try is [my current using this app]
2. you are very important is tom.and.jerry1995@gmail.com send the mail ,Viber ph+ or Discord , not facebook
